import { ApiProperty } from '@nestjs/swagger';
import { IsString, IsOptional, IsBoolean, IsObject } from 'class-validator';

export class SaveResumeDto {
  @ApiProperty({
    description: 'Resume content in markdown format',
    example: '# John Doe\n**Software Developer**\n\n## Contact\n- Email: john@example.com',
  })
  @IsString()
  content: string;

  @ApiProperty({
    description: 'Content format',
    example: 'markdown',
    default: 'markdown',
  })
  @IsOptional()
  @IsString()
  format?: string = 'markdown';

  @ApiProperty({
    description: 'Whether the resume was generated by AI',
    example: false,
    default: false,
  })
  @IsOptional()
  @IsBoolean()
  isGeneratedByAi?: boolean = false;

  @ApiProperty({
    description: 'Additional metadata for the resume',
    example: {
      lastModified: '2024-01-01T00:00:00.000Z',
      version: 1,
      wordCount: 250,
    },
    required: false,
  })
  @IsOptional()
  @IsObject()
  metadata?: {
    lastModified?: string;
    version?: number;
    wordCount?: number;
    [key: string]: any;
  };
}
